WorkFlow:

Credit Card Data ([Download Dataset](https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud))

↓

Data PreProcessing

↓

Data Analysis

↓

Train Test Split Dataset

↓

Logistic Regression

↓

Evaluation

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('creditcard.csv')

In [3]:
df.shape

(284807, 31)

In [4]:
df.head()

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [5]:
df.tail()

            Time         V1         V2  ...       V28  Amount  Class
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[5 rows x 31 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

Data is very unbalanced as Fraudlent Transactions are only 492 and rest are the otherwise. So we have to balanced the data before analyzing

In [9]:
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [10]:
print(legit.shape, fraud.shape)

(284315, 31) (492, 31)

In [11]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [12]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [13]:
# compare the vales for both

df.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28      Amount
Class                                    ...
0      94838.202258  0.008258 -0.006271  ... -0.000295 -0.000131   88.291022
1      80746.806911 -4.771948  3.623778  ...  0.170575  0.075667  122.211321

[2 rows x 30 columns]

Cleaning the data using **under-sampling** method

Build a sample dataset containing similar distribution of both transactions.

In [14]:
# Select random values
legit_sample = legit.sample(n=492)

In [15]:
# Concatenating

dataset = pd.concat([legit_sample, fraud], axis=0)

In [16]:
dataset.head()

            Time        V1        V2  ...       V28  Amount  Class
100487   67531.0 -1.052537 -0.084218  ...  0.172153     3.0      0
108238   70822.0 -0.631718  0.771971  ... -0.207509    55.0      0
59736    48976.0 -0.935746  1.024329  ...  0.093531     1.0      0
249221  154301.0  1.824186 -0.172038  ... -0.060092   104.0      0
163001  115559.0 -1.214011 -0.259087  ... -0.452620    15.0      0

[5 rows x 31 columns]

In [17]:
dataset.Class.value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [19]:
dataset.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28      Amount
Class                                    ...
0      97155.111789  0.046369  0.002814  ... -0.048012 -0.021967   70.147622
1      80746.806911 -4.771948  3.623778  ...  0.170575  0.075667  122.211321

[2 rows x 30 columns]

In [20]:
X = dataset.drop(columns='Class', axis=1)
Y = dataset.Class

In [21]:
print(X.shape, Y.shape)

(984, 30) (984,)

In [22]:
print(X)

            Time        V1        V2  ...       V27       V28  Amount
100487   67531.0 -1.052537 -0.084218  ...  0.461969  0.172153    3.00
108238   70822.0 -0.631718  0.771971  ... -0.152099 -0.207509   55.00
59736    48976.0 -0.935746  1.024329  ...  0.306376  0.093531    1.00
249221  154301.0  1.824186 -0.172038  ... -0.040500 -0.060092  104.00
163001  115559.0 -1.214011 -0.259087  ... -0.388063 -0.452620   15.00
...          ...       ...       ...  ...       ...       ...     ...
279863  169142.0 -1.927883  1.125653  ...  0.292680  0.147968  390.00
280143  169347.0  1.378559  1.289381  ...  0.389152  0.186637    0.76
280149  169351.0 -0.676143  1.126366  ...  0.385107  0.194361   77.89
281144  169966.0 -3.113832  0.585864  ...  0.884876 -0.253700  245.00
281674  170348.0  1.991976  0.158476  ...  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [23]:
print(Y)

100487    0
108238    0
59736     0
249221    0
163001    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [24]:
X_train, X_test, Y_train, Y_Test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [25]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

In [26]:
model = LogisticRegression()

In [27]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [28]:
train_prediction = model.predict(X_train)
train_accuracy = accuracy_score(train_prediction, Y_train)
print('Accuracy on Training data : ', train_accuracy)

Accuracy on Training data :  0.9504447268106735

In [30]:
test_prediction = model.predict(X_test)
test_accuracy = accuracy_score(test_prediction, Y_Test)
print('Accuracy on Testing data : ', test_accuracy)

Accuracy on Testing data :  0.9289340101522843